[build-system]
requires = ['flit_core >=3,<4']
build-backend = 'flit_core.buildapi'

[project]
name = "torch"
description = "Tensors and Dynamic neural networks in Python with strong GPU acceleration"
version = "2.8.0"
requires-python = ">=3.10"
license = "BSD-3-Clause"
dependencies = [
    'filelock',
    'typing-extensions>=4.10.0',
    'setuptools; python_version >= "3.12"',
    'sympy>=1.13.3',
    'networkx',
    'jinja2',
    'fsspec',

    # Common to all CUDA Variants
    'triton==3.4.0; platform_system == "Linux" and "nvidia" in variant_namespaces',
    'nvidia-cudnn==9.10.2.21; platform_system == "Linux" and platform_machine == "x86_64" and "nvidia" in variant_namespaces',
    'nvidia-cusparselt==0.7.1; platform_system == "Linux" and platform_machine == "x86_64" and "nvidia" in variant_namespaces',
    'nvidia-nccl==2.27.3; platform_system == "Linux" and platform_machine == "x86_64" and "nvidia" in variant_namespaces',

    # CUDA 12.6
    'nvidia-cuda-nvrtc==12.6.77; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cuda-runtime==12.6.77; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cuda-cupti==12.6.80; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cublas==12.6.4.1; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cufft==11.3.0.4; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-curand==10.3.7.77; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cusolver==11.7.1.2; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cusparse==12.5.4.2; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-nvtx==12.6.77; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-nvjitlink==12.6.85; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',
    'nvidia-cufile==1.11.1.6; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.6"',

    # CUDA 12.8
    'nvidia-cuda-nvrtc==12.8.93; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cuda-runtime==12.8.90; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cuda-cupti==12.8.90; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cublas==12.8.4.1; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cufft==11.3.3.83; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-curand==10.3.9.90; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cusolver==11.7.3.90; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cusparse==12.5.8.93; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-nvtx==12.8.90; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-nvjitlink==12.8.93; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',
    'nvidia-cufile==1.13.1.3; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.8"',

    # CUDA 12.9
    'nvidia-cuda-nvrtc==12.9.86; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cuda-runtime==12.9.79; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cuda-cupti==12.9.79; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cublas==12.9.1.4; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cufft==11.4.1.4; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-curand==10.3.10.19; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cusolver==11.7.5.82; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cusparse==12.5.10.65; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-nvtx==12.9.79; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-nvjitlink==12.9.86; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
    'nvidia-cufile==1.14.1.1; platform_system == "Linux" and platform_machine == "x86_64" and variant_label == "cuda12.9"',
]

[project.urls]
"Homepage" = "https://pytorch.org/"
"Documentation" = "https://pytorch.org/docs/"
"Source" = "https://github.com/pytorch/pytorch"
"Forum" = "https://discuss.pytorch.org/"

[variant.default-priorities]
namespace = ["nvidia", "priority"]

[variant.providers.nvidia]
requires = ["nvidia-variant-provider>=0.0.2,<1.0.0"]
plugin-api = "nvidia_variant_provider.plugin:NvidiaVariantPlugin"
enable-if = "platform_system == 'Linux' or platform_system == 'Windows'"

[variant.providers.priority]
install-time = false

[variant.static-properties.priority]
order = ["1", "2", "3"]
